version: "3.8"

services:
  # --- 1. DATABASE SERVICE ---
  db_service:
    image: mysql:8.0
    container_name: db_hustlink
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-hustlink_db}
      MYSQL_USER: ${DB_USER:-hustlink_user}
      MYSQL_PASSWORD: ${DB_PASS:-hustlink_pass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-rootpassword}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # --- 2. APP SERVICE ---
  app_service:
    build: ./app
    container_name: app_hustlink
    restart: always
    expose:
      - "3000"
    environment:
      - DB_HOST=db_service
      - DB_USER=${DB_USER:-hustlink_user}
      - DB_PASS=${DB_PASS:-hustlink_pass}
      - DB_NAME=${DB_NAME:-hustlink_db}
      - APP_PORT=3000
    depends_on:
      db_service:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

  # --- 3. NGINX SERVICE ---
  nginx_service:
    image: nginx:alpine
    container_name: nginx_hustlink
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - app_network

#--- VOLUMES AND NETWORKS ---
volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge